on:
  push:
    branches:
      - master
    paths:
      - redis/**
      - .github/workflows/ci-redis.yaml
  pull_request:
    paths:
      - redis/**
      - .github/workflows/ci-redis.yaml

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/ppc64le
    steps:
      - uses: actions/checkout@v3

      - name: Get version
        id: version
        working-directory: redis
        run: |
          DOCKER_TAG="$(grep --color=never -oP 'bitnami/redis:\K\S+' Dockerfile)"
          echo "version=${DOCKER_TAG}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          platforms: ${{ env.PLATFORMS }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:redis"
          push: false
          build-args: |
            VERSION=${{ steps.version.outputs.version }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
