on:
  push:
    branches:
      - master
    paths:
      - wait-for-port/**
      - .github/workflows/ci-wait-for-port.yaml
  pull_request:
    paths:
      - wait-for-port/**
      - .github/workflows/ci-wait-for-port.yaml

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/ppc64le,linux/s390x
    steps:
      - uses: actions/checkout@v3

      - name: Get version
        id: version
        working-directory: wait-for-port
        run: |
          GH_TAG="$(go list -f '{{ .Version }}' -m 'github.com/bitnami/wait-for-port')"
          echo "version=${GH_TAG}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          platforms: ${{ env.PLATFORMS }}

      - name: Enable buildkit cache
        uses: actions/cache@v3
        with:
          path: /tmp/buildkit-cache/buildkit-state.tar
          key: ${{ runner.os }}-buildkit-${{ steps.version.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-buildkit-

      - name: Load buildkit state from cache
        uses: dashevo/gh-action-cache-buildkit-state@v1
        with:
          builder: buildx_buildkit_${{ steps.buildx.outputs.name }}0
          cache-path: /tmp/buildkit-cache
          cache-max-size: 8g

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:wait-for-port"
          push: false
          build-args: |
            VERSION=${{ steps.version.outputs.version }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
