on:
  release:
    types: [released]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name, 'wait-for-port@')
    env:
      DOCKERHUB_USERNAME: isac322
      PLATFORMS: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/ppc64le
    steps:
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          flavor: latest=true
          images: ${{ env.DOCKERHUB_USERNAME }}/wait-for-port
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            maintainer=${{ env.DOCKERHUB_USERNAME }}
            org.opencontainers.image.title=wait-for-port
            org.opencontainers.image.source=https://github.com/bitnami/wait-for-port

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Enable buildkit cache
        uses: actions/cache@v3
        with:
          path: /tmp/buildkit-cache/buildkit-state.tar
          key: ${{ runner.os }}-buildkit-${{ steps.docker_meta.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-buildkit-

      - name: Load buildkit state from cache
        uses: dashevo/gh-action-cache-buildkit-state@v1
        with:
          builder: buildx_buildkit_${{ steps.buildx.outputs.name }}0
          cache-path: /tmp/buildkit-cache
          cache-max-size: 8g

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:wait-for-port"
          push: true
          build-args: |
            VERSION=${{ steps.docker_meta.outputs.version }}
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
